apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-api
  labels:
    app: security-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-api
  template:
    metadata:
      labels:
        app: security-api
    spec:
      containers:
      - name: security-api
        image: ubik-security-api-test:latest
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AuthServer__MetadataAddress
          value: "http://keycloak-local:8080/realms/ubik/.well-known/openid-configuration"
        - name: AuthServer__Authority
          value: "http://keycloak-local:8080/realms/ubik"
        - name: AuthServer__AuthorizationUrl
          value: "http://keycloak-local:8080/realms/ubik/protocol/openid-connect/auth"
        - name: AuthServer__TokenUrl
          value: "http://keycloak-local:8080/realms/ubik/.protocol/openid-connect/token"
        - name: ConnectionStrings__SecurityDbContext
          value: "Host=ubik-postgres-postgresql;Port=5432;Database=ubik_security;Username=postgres;Password=test01"
        - name: AuthManagerKeyCloakClient__RootUrl
          value: "http://keycloak-local:8080/"
        - name: MessageBroker__Host
          value: "amqp://ubik-rabbitmq:5672"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: security-api
  labels:
    app: security-api
spec:
  selector:
    app: security-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
