# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build_and_test_2

on:
  push:
    branches: [ "tenants_and_users" ]
  pull_request:
    branches: [ "tenants_and_users" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        compose-file: "docker-compose.yml,build_and_test_new_on_tenant_users_branch.yml" 
      run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Debug --no-restore
    - name: Test
      run: dotnet test -c Debug --no-build --no-restore
